{{- if .Values.dbCredentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dbCredentials.secretName }}
  namespace: {{ .Values.operatorNamespace }}
  labels:
    {{- include "korsair.labels" . | nindent 4 }}
    app.kubernetes.io/component: db
type: Opaque
data:
  username: {{ .Values.dbCredentials.username | b64enc | quote }}
  password: {{ .Values.dbCredentials.password | b64enc | quote }}
  database: {{ .Values.dbCredentials.database | b64enc | quote }}
  postgres-password: {{ .Values.dbCredentials.password | b64enc | quote }}
{{- end }}
