{{- if and .Values.registryCredentials.enabled (not .Values.registryCredentials.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.registryCredentials.secretName }}
  namespace: {{ .Values.operatorNamespace }}
  labels:
    {{- include "korsair.labels" . | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ dict "auths" (dict .Values.registryCredentials.server (dict "username" .Values.registryCredentials.username "password" .Values.registryCredentials.password "auth" (printf "%s:%s" .Values.registryCredentials.username .Values.registryCredentials.password | b64enc))) | toJson | b64enc }}
{{- end }}
